In [ ]:
import numpy as np
vector= np.random.randint(1,101,100).reshap

In [1]:
import numpy as np
vector= np.random.randint(0,90,27).reshape(3,3,3)
print(vector)

[[[ 4  2 41]
  [27 54 25]
  [11 55 31]]

 [[83 77 76]
  [29 57 73]
  [ 0 46 78]]

 [[41 83 87]
  [70 62 27]
  [71 62 75]]]
