In [ ]:
import numpy as np
X = np.random.randn(100) # random 1D array
N = 100
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[[1 4 1]
 [0 1 2]
 [3 1 4]
 [1 4 1]
 [2 4 3]
 [0 2 1]
 [4 0 0]
 [4 1 0]
 [0 4 1]
 [0 3 4]]
[[1 4 1]
 [0 1 2]
 [3 1 4]
 [1 4 1]
 [2 4 3]
 [0 2 1]
 [4 0 0]
 [4 1 0]
 [0 4 1]
 [0 3 4]]
[[1 4 1]
 [0 1 2]
 [3 1 4]
 [1 4 1]
 [2 4 3]
 [0 2 1]
 [4 0 0]
 [4 1 0]
 [0 4 1]
 [0 3 4]]


In [ ]:
import numpy as np
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


In [ ]:
import numpy as np
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]]
