In [2]:
import numpy as np
vector= np.random.randint(1,101,100).reshape(10,10)
print(vector,vector.min(),vector.max())

[[74 14 27 58 35 60 77 36 82 25]
 [79 54 75  8 63 69 29 57 68 86]
 [39 89 12 91 98 31 43 63 10  4]
 [53  8 26 26 92 39  7  2  9 69]
 [51 20 94 34 48 58 93 24 54 50]
 [98 40 21 74 38 43 38 43 12  6]
 [52 70 56 71 27 70 99 38 19 63]
 [57 37 63 50 69 21 48 90 33 39]
 [84 57 31 78 30 88  1 33 49 89]
 [89 99 31 88  6 89 40 92 36 66]] 1 99


In [1]:
import numpy as np
vector= np.random.randint(0,90,27).reshape(3,3,3)
print(vector)

[[[ 4  2 41]
  [27 54 25]
  [11 55 31]]

 [[83 77 76]
  [29 57 73]
  [ 0 46 78]]

 [[41 83 87]
  [70 62 27]
  [71 62 75]]]


In [2]:
import numpy as np
vector= np.identity(3)
print(vector)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
