In [1]:
import numpy as np
vector= np.random.randint(1,101,100).reshape(10,10)
print(vector,vector.min(),vector.max())

[[ 33   1  17  57  51  78  26  61  61  20]
 [ 60  72  49  20  55  78  64   4  38  58]
 [ 13  25  39   8  19  42  52  70  63  81]
 [  9  25  75  95  37  13   1  35   6  73]
 [ 33  30  61  18  67  32  30  64  44   7]
 [100  40 100  94  96  89  23  78  11  13]
 [ 98  24  86  85  35  87  64  24  14  10]
 [ 36  80  91  47  93   2  25  13  72   2]
 [ 64  83  16  86  85  24  10  74  48  99]
 [ 83   1  87  21  42  59  26  65  73  41]] 1 100
