In [5]:
import numpy as np
v=np.arange(25).reshape(5,5)
v=(v - np.mean (v)) / (np.std (v))
print(v)

[[-1.66410059 -1.52542554 -1.38675049 -1.24807544 -1.10940039]
 [-0.97072534 -0.83205029 -0.69337525 -0.5547002  -0.41602515]
 [-0.2773501  -0.13867505  0.          0.13867505  0.2773501 ]
 [ 0.41602515  0.5547002   0.69337525  0.83205029  0.97072534]
 [ 1.10940039  1.24807544  1.38675049  1.52542554  1.66410059]]
