In [1]:
import numpy as np
v=np.random.uniform(0,10,10)
print (v - v%1)
print (np.floor(v))
print (np.ceil(v)-1)
print (v.astype(int))

[6. 3. 6. 9. 8. 4. 9. 1. 3. 0.]
[6. 3. 6. 9. 8. 4. 9. 1. 3. 0.]
[6. 3. 6. 9. 8. 4. 9. 1. 3. 0.]
[6 3 6 9 8 4 9 1 3 0]
