In [4]:
import numpy as np
v = np.random.randint(0,10,(3,4,3,4))
print(v)
sum = A.sum(axis=(-2,-1))
print(sum)

[[[[2 2 8 4]
   [1 4 7 7]
   [0 1 6 8]]

  [[0 4 3 8]
   [8 8 3 4]
   [3 7 9 7]]

  [[2 6 9 2]
   [7 0 7 8]
   [2 4 5 2]]

  [[4 1 9 5]
   [2 8 1 0]
   [1 2 7 7]]]


 [[[4 4 0 0]
   [5 9 1 0]
   [2 8 6 8]]

  [[9 7 3 3]
   [7 5 5 2]
   [9 7 2 3]]

  [[7 6 1 4]
   [5 0 3 9]
   [2 0 3 6]]

  [[2 3 6 5]
   [7 3 2 2]
   [5 6 0 2]]]


 [[[8 3 2 2]
   [0 2 4 5]
   [2 6 1 6]]

  [[0 7 8 6]
   [5 3 8 7]
   [9 9 4 2]]

  [[3 5 0 0]
   [6 1 9 4]
   [8 8 2 7]]

  [[5 6 8 3]
   [2 5 8 6]
   [3 0 3 4]]]]
[[54 57 76 48]
 [44 46 61 49]
 [58 51 44 38]]
