In [1]:
import numpy as np
v = np.random.randint(0,10,(5,5))
print(v)
v[[0,1]] = v[[1,0]]
print(v)

[[8 1 3 7 0]
 [8 6 5 2 0]
 [0 9 0 9 6]
 [2 2 5 9 4]
 [3 1 1 0 6]]
[[8 6 5 2 0]
 [8 1 3 7 0]
 [0 9 0 9 6]
 [2 2 5 9 4]
 [3 1 1 0 6]]
