In [4]:
import numpy as np
x = np.ones((5,5,3))
y = np.random.randint(0,10,(5,5))
print(x * y[:,:,None])

[[[3. 3. 3.]
  [8. 8. 8.]
  [6. 6. 6.]
  [1. 1. 1.]
  [6. 6. 6.]]

 [[3. 3. 3.]
  [4. 4. 4.]
  [0. 0. 0.]
  [0. 0. 0.]
  [8. 8. 8.]]

 [[6. 6. 6.]
  [2. 2. 2.]
  [3. 3. 3.]
  [3. 3. 3.]
  [7. 7. 7.]]

 [[4. 4. 4.]
  [9. 9. 9.]
  [4. 4. 4.]
  [4. 4. 4.]
  [0. 0. 0.]]

 [[9. 9. 9.]
  [0. 0. 0.]
  [5. 5. 5.]
  [9. 9. 9.]
  [8. 8. 8.]]]
