In [1]:
import numpy as np
from numpy.lib import stride_tricks

def g(a, w):
    s = (a.size - w + 1, w)
    st = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=s, strides=st)
x = g(np.arange(10), 3)
print(x)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
