In [1]:
import numpy as np
v = np.ones((16,16))
k = 4
x = np.add.reduceat(np.add.reduceat(v, np.arange(0, v.shape[0], k), axis=0),
                                       np.arange(0, v.shape[1], k), axis=1)
print(x)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
