In [3]:
import numpy as np
from numpy.lib import stride_tricks
v = np.arange(1,15,dtype=np.uint32)
x = stride_tricks.as_strided(v,(11,4),(4,4))
print(x)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
