In [3]:
import numpy as np
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)


[[1 4 1]
 [0 1 2]
 [3 1 4]
 [1 4 1]
 [2 4 3]
 [0 2 1]
 [4 0 0]
 [4 1 0]
 [0 4 1]
 [0 3 4]]
[[1 4 1]
 [0 1 2]
 [3 1 4]
 [1 4 1]
 [2 4 3]
 [0 2 1]
 [4 0 0]
 [4 1 0]
 [0 4 1]
 [0 3 4]]
[[1 4 1]
 [0 1 2]
 [3 1 4]
 [1 4 1]
 [2 4 3]
 [0 2 1]
 [4 0 0]
 [4 1 0]
 [0 4 1]
 [0 3 4]]
