In [4]:
import numpy as np
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]]
